### PR TITLE
increase max description column size

### PR DESCRIPTION
**Pull request by cmsimike**
allow for a much bigger description column

### CODE REVIEW

**Comment by cmsimike** [comment]
this resolves #29

**Comment by cmsimike** [comment]
this resolves #28

**Comment by zorgiepoo** [comment]
Thank you for the pull request! I agree that the description column should allow for a bigger maximum column width. You've also (probably accidentally) decreased the default/initial width from 264 to 43 however. Could you please revert that part of the change so that the initial width doesn't turn out to be very small?

**Comment by cmsimike** [comment]
Sorry about that. Should be fixed now.

**Comment by zorgiepoo** [comment]
Thanks for the contribution! It's been merged.

**Pull request merged**
